import Head from 'next/head'
import { Public_Sans } from 'next/font/google'
import styles from '@/styles/Home.module.sass'
import Main from '@/components/Main'

const publicSans = Public_Sans({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.container} ${publicSans.className}`}>
        <Main />
      </main>
    </>
  )
}
